# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Zhi's website"
tagline:          "Shout out to J"
description:      "it's me z c:"
url:              https://onezhi.me
baseurl:          /

paginate:         5

plugins: [jekyll-paginate, jekyll-gist]